#!/bin/sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
LOG_FILE="$REPO_ROOT/hook.log"
NODE_EXE="$(command -v node)"

unset NODE_OPTIONS
unset VSCODE_INSPECTOR_OPTIONS
unset ELECTRON_RUN_AS_NODE

echo "hook started" >> "$LOG_FILE"
echo "repo: $REPO_ROOT" >> "$LOG_FILE"
echo "node: $NODE_EXE" >> "$LOG_FILE"

"$NODE_EXE" "$REPO_ROOT/scripts/print-latest.js" >> "$LOG_FILE" 2>&1 &
echo "hook spawned background process" >> "$LOG_FILE"
#put this file in .git
exit 0
